balancing-group:
  auth:
    test:
      https://testcas.epias.com.tr
    prod:
      https://cas.epias.com.tr
  service_config:
    test:
      https://epys-prp.epias.com.tr
    prod:
      https://epys.epias.com.tr
    service_ticket:
      prod:
        https://epys.epias.com.tr
      test:
        https://epys.epias.com.tr
        
customer:
  auth:
    test:
      https://testcas.epias.com.tr
    prod:
      https://cas.epias.com.tr
  service_config:
    test:
      https://epys-prp.epias.com.tr
    prod:
      https://epys.epias.com.tr
    service_ticket:
      prod:
        https://epys.epias.com.tr
      test:
        https://epys-prp.epias.com.tr

gop:
  auth:
    test:
      https://testcas.epias.com.tr
    prod:
      https://cas.epias.com.tr
  service_config:
    test:
      https://testgop.epias.com.tr
    prod:
      https://gop.epias.com.tr
    service_ticket:
      prod:
        https://gop.epias.com.tr
      test:
        https://testgop.epias.com.tr

grid:
  auth:
    test:
      https://testcas.epias.com.tr
    prod:
      https://cas.epias.com.tr
  service_config:
    test:
      https://epys-prp.epias.com.tr
    prod:
      https://epys.epias.com.tr
    service_ticket:
      prod:
        https://epys.epias.com.tr
      test:
        https://epys-prp.epias.com.tr

gunici:
  auth:
    test:
      https://testcas.epias.com.tr
    prod:
      https://cas.epias.com.tr
  service_config:
    test:
      https://gunici-prp.epias.com.tr
    prod:
      https://gunici.epias.com.tr
    service_ticket:
      prod:
        https://gunici.epias.com.tr
      test:
        https://gunici-prp.epias.com.tr

gunici-trading:
  auth:
    test:
      https://testcas.epias.com.tr
    prod:
      https://cas.epias.com.tr
  service_config:
    test:
      https://gunici-prp.epias.com.tr
    prod:
      https://gunici.epias.com.tr
    service_ticket:
      prod:
        https://gunici.epias.com.tr
      test:
        https://gunici-prp.epias.com.tr

pre-reconciliation:
  auth:
    test:
      https://testcas.epias.com.tr
    prod:
      https://cas.epias.com.tr
  service_config:
    test:
      https://epys-prp.epias.com.tr
    prod:
      https://epys.epias.com.tr
    service_ticket:
      prod:
        https://epys.epias.com.tr
      test:
        https://epys-prp.epias.com.tr

reconciliation-bpm:
  auth:
    test:
      https://testcas.epias.com.tr
    prod:
      https://cas.epias.com.tr
  service_config:
    test:
      https://epys-prp.epias.com.tr
    prod:
      https://epys.epias.com.tr
    service_ticket:
      prod:
        https://epys.epias.com.tr
      test:
        https://epys-prp.epias.com.tr

reconciliation-imbalance:
  auth:
    test:
      https://testcas.epias.com.tr
    prod:
      https://cas.epias.com.tr
  service_config:
    test:
      https://epys-prp.epias.com.tr
    prod:
      https://epys.epias.com.tr
    service_ticket:
      prod:
        https://epys.epias.com.tr
      test:
        https://epys-prp.epias.com.tr
    
reconciliation-invoice
  auth:
    test:
      https://testcas.epias.com.tr
    prod:
      https://cas.epias.com.tr
  service_config:
    test:
      https://epys-prp.epias.com.tr
    prod:
      https://epys.epias.com.tr
    service_ticket:
      prod:
        https://epys.epias.com.tr
      test:
        https://epys-prp.epias.com.tr
reconciliation-market
  auth:
    test:
      https://testcas.epias.com.tr
    prod:
      https://cas.epias.com.tr
  service_config:
    test:
      https://epys-prp.epias.com.tr
    prod:
      https://epys.epias.com.tr
    service_ticket:
      prod:
        https://epys.epias.com.tr
      test:
        https://epys-prp.epias.com.tr
reconciliation-mof
  auth:
    test:
      https://testcas.epias.com.tr
    prod:
      https://cas.epias.com.tr
  service_config:
    test:
      https://epys-prp.epias.com.tr
    prod:
      https://epys.epias.com.tr
    service_ticket:
      prod:
        https://epys.epias.com.tr
      test:
        https://epys-prp.epias.com.tr
reconciliation-res
  auth:
    test:
      https://testcas.epias.com.tr
    prod:
      https://cas.epias.com.tr
  service_config:
    test:
      https://epys-prp.epias.com.tr
    prod:
      https://epys.epias.com.tr
    service_ticket:
      prod:
        https://epys.epias.com.tr
      test:
        https://epys-prp.epias.com.tr
registration
  auth:
    test:
      https://testcas.epias.com.tr
    prod:
      https://cas.epias.com.tr
  service_config:
    test:
      https://epys-prp.epias.com.tr
    prod:
      https://epys.epias.com.tr
    service_ticket:
      prod:
        https://epys.epias.com.tr
      test:
        https://epys-prp.epias.com.tr
