endpoints:
  non-registered-metering-point-application-apply:
    endpoint: /v1/non-registered-metering-point-application/apply
    method: POST
    auth: true
    short_name: non-registered-metering-point-application-apply
    short_name_tr: KMO Başvurusu Yap
    params:
    - supplierOrganizationId
    - readingOrganizationId
    - uniqueCode
    - categoryType
    - customerName
    - customerNo
    - authorizedPerson1Name
    - authorizedPerson1No
    - authorizedPerson2Name
    - authorizedPerson2No
    - isPrecheck
    required:
    - categoryType
    - customerName
    - customerNo
    - readingOrganizationId
    - uniqueCode
    response: Response
    var_type:
    - name: body
      var_type: object
      description: ''
      required: false
      properties:
        supplierOrganizationId:
          type: int
          description: Tedarikçi organizasyon id
        readingOrganizationId:
          type: int
          description: Sayaç okuyan kurum id
          required: true
        uniqueCode:
          type: str
          description: Tekil kod
          required: true
        categoryType:
          type: int
          description: Abone kategori tipi lookup değeridir
          required: true
        customerName:
          type: str
          description: Tüketici ad/soyad veya ünvan bilgisi
          required: true
        customerNo:
          type: str
          description: Abone tüketici no bilgisi
          required: true
        authorizedPerson1Name:
          type: str
          description: Birinci yetkili kişi ad/soyad bilgisi
        authorizedPerson1No:
          type: str
          description: Birinci yetkili kişi tckn bilgisi
        authorizedPerson2Name:
          type: str
          description: İkinci yetkili kişi ad/soyad bilgisi
        authorizedPerson2No:
          type: str
          description: İkinci yetkili kişi tckn bilgisi
        isPrecheck:
          type: bool
          description: Önyüz kullanımı için hazırlanmış istek sonucunda oluşacak durumlarla alakalı kayıt oluşmadan önce geri dönüş alabilmek için konulan ön kontrol değeridir
    summary: KMO Başvurusu Yap
    description: Kaydı mevcut olmayan ölçüm noktası başvuru kaydetme servisidir
    response_structure:
      status: string
      correlationId: string
      spanIds: string
      hostName: string
      clientIp: string
      userName: string
      successMessage: string
      errors:
      - errorCode: string
        errorMessage: string
      unsuccessfulList:
      - {}
      dispatch: string
      body:
        content:
          supplierOrganizationId: integer
          supplierOrganizationName: string
          readingOrganizationId: integer
          readingOrganizationName: string
          uniqueCode: string
          eic: string
          customerName: string
          customerNo: string
          authorizedPerson1Name: string
          authorizedPerson1No: string
          authorizedPerson2Name: string
          authorizedPerson2No: string
          isCustomerNoUnique: boolean
          applicationType:
            id: integer
            value: string
            localizations:
            - language: string
              text: string
          categoryType:
            id: integer
            value: string
            localizations:
            - language: string
              text: string
          demandStatus:
            id: integer
            value: string
            localizations:
            - language: string
              text: string
          periodDate: string
  non-registered-metering-point-application-query:
    endpoint: /v1/non-registered-metering-point-application/query
    method: POST
    auth: true
    short_name: non-registered-metering-point-application-query
    short_name_tr: KMO Taleplerini Sorgula
    params:
    - page
    - supplierOrganizationId
    - supplierOrganizationIdContains
    - uniqueCode
    - uniqueCodeContains
    - readingOrganizationId
    - readingOrganizationIdContains
    - eic
    - eicContains
    - categoryTypes
    - customerName
    - customerNameContains
    - applicationTypes
    - demandStatuses
    - periodDate
    required: []
    response: Response
    var_type:
    - name: body
      var_type: object
      description: ''
      required: false
      properties:
        page:
          type: str
          properties:
            number:
              type: int
              description: ${VALUE_PAGE_NUMBER}
              example: ${EXAMPLE_PAGE_NUMBER}
            size:
              type: int
              description: ${VALUE_PAGE_SIZE}
              example: ${EXAMPLE_PAGE_SIZE}
            total:
              type: int
              description: ${VALUE_PAGE_TOTAL}
              example: ${EXAMPLE_PAGE_TOTAL}
            sort:
              type: str
              description: ${VALUE_PAGE_SORT}
              properties:
                field:
                  type: str
                  description: ${VALUE_SORT_FIELD}
                  example: ${EXAMPLE_SORT_FIELD}
                direction:
                  type: str
                  description: ${VALUE_SORT_DIRECTION}
                  example: ASC
        supplierOrganizationId:
          type: int
          description: Tedarikçi organizasyon id
        supplierOrganizationIdContains:
          type: int
          description: Tedarikçi organizasyon id (İçinde ara)
        uniqueCode:
          type: str
          description: Tekil kod
        uniqueCodeContains:
          type: str
          description: Tekil kod (İçinde ara)
        readingOrganizationId:
          type: int
          description: Sayaç okuyan kurum id
        readingOrganizationIdContains:
          type: int
          description: Sayaç okuyan kurum id (İçinde ara)
        eic:
          type: str
          description: Sayaca ait enerji tanımlama kodu (EIC)
          example: 40X000000000002C
        eicContains:
          type: str
          description: Sayaca ait enerji tanımlama kodu (EIC) (İçinde ara)
        categoryTypes:
          type: list
          description: Abone kategori tipi lookup değeridir
          items: int
        customerName:
          type: str
          description: Tüketici ad/soyad veya ünvan bilgisi
        customerNameContains:
          type: str
          description: Tüketici ad/soyad veya ünvan bilgisi (İçinde ara)
        applicationTypes:
          type: list
          description: Kaydı mevcut olmayan ölçüm noktası başvuru tipi lookup değeridir
          items: int
        demandStatuses:
          type: list
          description: Kaydı mevcut olmayan ölçüm noktası başvuru durumu lookup değeridir
          items: int
        periodDate:
          type: datetime
          description: Dönem bilgisi
          example: '["2020-01-01T00:00:00+03:00"]'
    summary: KMO Taleplerini Sorgula
    description: Kaydı mevcut olmayan ölçüm noktası taleplerinin sorgulama servisidir
    response_structure:
      status: string
      correlationId: string
      spanIds: string
      hostName: string
      clientIp: string
      userName: string
      successMessage: string
      errors:
      - errorCode: string
        errorMessage: string
      unsuccessfulList:
      - {}
      dispatch: string
      body:
        content:
          items:
          - id: integer
            supplierOrganizationId: integer
            supplierOrganizationName: string
            uniqueCode: string
            readingOrganizationId: integer
            readingOrganizationName: string
            eic: string
            categoryType:
              id: integer
              value: string
              localizations:
              - '...'
            customerName: string
            customerNo: string
            authorizedPerson1Name: string
            authorizedPerson1No: string
            authorizedPerson2Name: string
            authorizedPerson2No: string
            applicationType:
              id: integer
              value: string
              localizations:
              - '...'
            demandStatus:
              id: integer
              value: string
              localizations:
              - '...'
            meteringPointStatus:
              id: integer
              value: string
              localizations:
              - '...'
            explanation:
              id: integer
              value: string
              localizations:
              - '...'
            periodDate: string
          page:
            number: integer
            size: integer
            total: integer
            sort:
              field: string
              direction: string
          sortableFields:
          - string
  non-registered-metering-point-application-reject:
    endpoint: /v1/non-registered-metering-point-application/reject
    method: POST
    auth: true
    short_name: non-registered-metering-point-application-reject
    short_name_tr: KMO Başvurusu Reddet
    params:
    - ids
    required:
    - ids
    response: Response
    var_type:
    - name: body
      var_type: object
      description: ''
      required: false
      properties:
        ids:
          type: list
          description: Kaydı mevcut olmayan ölçüm noktası başvuru id
          required: true
          items: int
    summary: KMO Başvurusu Reddet
    description: Kaydı mevcut olmayan ölçüm noktası talebini reddetme servisidir
    response_structure:
      status: string
      correlationId: string
      spanIds: string
      hostName: string
      clientIp: string
      userName: string
      successMessage: string
      errors:
      - errorCode: string
        errorMessage: string
      unsuccessfulList:
      - {}
      dispatch: string
      body:
        content:
          completed: boolean
  non-registered-metering-point-application-withdraw:
    endpoint: /v1/non-registered-metering-point-application/withdraw
    method: POST
    auth: true
    short_name: non-registered-metering-point-application-withdraw
    short_name_tr: KMO Başvurusu Geri Çek
    params:
    - id
    required:
    - id
    response: Response
    var_type:
    - name: body
      var_type: object
      description: ''
      required: false
      properties:
        id:
          type: int
          description: Kaydı mevcut olmayan ölçüm noktası başvuru id
          required: true
    summary: KMO Başvurusu Geri Çek
    description: Kaydı mevcut olmayan ölçüm noktası talebini geri çekme servisidir
    response_structure:
      status: string
      correlationId: string
      spanIds: string
      hostName: string
      clientIp: string
      userName: string
      successMessage: string
      errors:
      - errorCode: string
        errorMessage: string
      unsuccessfulList:
      - {}
      dispatch: string
      body:
        content:
          completed: boolean
