endpoints:
  dashboard_configs_save:
    endpoint: /rest/v1/dashboard-configs/update
    method: POST
    auth: true
    short_name: dashboard_configs_save
    short_name_tr: Dashboard konfigürasyon güncelleme
    params:
    - configs
    required: null
    response:
    - status
    - correlationId
    - spanIds
    - hostName
    - clientIp
    - userName
    - successMessage
    - errors
    - body
    var_type:
    - name: configs
      var_type: str
      description: ''
      required: false
    summary: Dashboard konfigürasyon güncelleme
    description: Dashboard konfigürasyon güncelleme
    response_structure:
      status: str
      txId: str
      hostName: str
      clientIp: str
      userName: str
      errors:
      - str
      body: str
      dispatch: str
  configs_get:
    endpoint: /rest/v1/configs
    method: GET
    auth: true
    short_name: configs_get
    short_name_tr: Ayarlaları sorgulama
    params: []
    required: null
    response:
    - status
    - correlationId
    - spanIds
    - hostName
    - clientIp
    - userName
    - successMessage
    - errors
    - body
    var_type: []
    summary: Ayarlaları sorgulama
    description: Ayarlaları sorgulama
    response_structure:
      status: str
      txId: str
      hostName: str
      clientIp: str
      userName: str
      errors:
      - str
      body: str
      dispatch: str
  dashboard_configs_get:
    endpoint: /rest/v1/dashboard-configs
    method: GET
    auth: true
    short_name: dashboard_configs_get
    short_name_tr: Dashboard konfigürasyonları sorgulama
    params: []
    required: null
    response:
    - status
    - correlationId
    - spanIds
    - hostName
    - clientIp
    - userName
    - successMessage
    - errors
    - body
    var_type: []
    summary: Dashboard konfigürasyonları sorgulama
    description: Dashboard konfigürasyonları sorgulama
    response_structure:
      status: str
      txId: str
      hostName: str
      clientIp: str
      userName: str
      errors:
      - str
      body: str
      dispatch: str
  list_organization_otr_dashboard:
    endpoint: /rest/v1/dashboard/otr/dashboard
    method: POST
    auth: true
    short_name: list_organization_otr_dashboard
    short_name_tr: Teklif Eşleşme Oran (TEO) Dashboardu
    params:
    - region
    required: null
    response:
    - status
    - correlationId
    - spanIds
    - hostName
    - clientIp
    - userName
    - successMessage
    - errors
    - body
    var_type:
    - name: region
      var_type: str
      description: Bölge
      required: false
    summary: Teklif Eşleşme Oran (TEO) Dashboardu
    description: Kontratlardaki teklif eşleşme oran bilgilerinin verildiği Dashboardu.
    response_structure:
      status: str
      txId: str
      hostName: str
      clientIp: str
      userName: str
      errors:
      - str
      body: str
      dispatch: str
  list_top_ten_otr_dashboard:
    endpoint: /rest/v1/dashboard/otr/top-ten
    method: POST
    auth: true
    short_name: list_top_ten_otr_dashboard
    short_name_tr: ${TOP_TEN_TEO_DASHBOARD}
    params:
    - region
    required: null
    response:
    - status
    - correlationId
    - spanIds
    - hostName
    - clientIp
    - userName
    - successMessage
    - errors
    - body
    var_type:
    - name: region
      var_type: str
      description: Bölge
      required: false
    summary: ${TOP_TEN_TEO_DASHBOARD}
    description: ${TOP_TEN_TEO_DASHBOARD_NOTE}
    response_structure:
      status: str
      txId: str
      hostName: str
      clientIp: str
      userName: str
      errors:
      - str
      body: str
      dispatch: str
  list_organization_otr_dashboard_export:
    endpoint: /rest/v1/dashboard/otr/dashboard/export
    method: POST
    auth: true
    short_name: list_organization_otr_dashboard_export
    short_name_tr: Teklif Eşleşme Oran (TEO) Raporu
    params:
    - region
    required: null
    response:
    - status
    - correlationId
    - spanIds
    - hostName
    - clientIp
    - userName
    - successMessage
    - errors
    - body
    var_type:
    - name: region
      var_type: str
      description: Bölge
      required: false
    summary: Teklif Eşleşme Oran (TEO) Raporu
    description: Kontratlardaki teklif eşleşme oran bilgilerinin verildiği rapor.
    response_structure:
      view: str
      model: dict
      status: str
      empty: bool
      reference: bool
      viewName: str
      modelMap: dict
  configs_save:
    endpoint: /rest/v1/configs/update
    method: POST
    auth: true
    short_name: configs_save
    short_name_tr: Ayarları güncelleme
    params:
    - language
    - region
    - theme
    - matchNotification
    - objectionNotification
    - contractTableConfig
    - sessionTime
    - notificationDisplayTime
    - contractDetailNotification
    - matchDetailNotification
    - hourlyDetailNotification
    - dailySummaryNotification
    required: null
    response:
    - status
    - correlationId
    - spanIds
    - hostName
    - clientIp
    - userName
    - successMessage
    - errors
    - body
    var_type:
    - name: language
      var_type: str
      description: ''
      required: false
    - name: region
      var_type: str
      description: Bölge
      required: false
    - name: theme
      var_type: str
      description: ''
      required: false
    - name: matchNotification
      var_type: bool
      description: ''
      required: false
    - name: objectionNotification
      var_type: bool
      description: ''
      required: false
    - name: contractTableConfig
      var_type: str
      description: ''
      required: false
    - name: sessionTime
      var_type: int
      description: ''
      required: false
    - name: notificationDisplayTime
      var_type: int
      description: ''
      required: false
    - name: contractDetailNotification
      var_type: str
      description: ''
      required: false
    - name: matchDetailNotification
      var_type: str
      description: ''
      required: false
    - name: hourlyDetailNotification
      var_type: str
      description: ''
      required: false
    - name: dailySummaryNotification
      var_type: str
      description: ''
      required: false
    summary: Ayarları güncelleme
    description: Ayarları güncelleme
    response_structure:
      status: str
      txId: str
      hostName: str
      clientIp: str
      userName: str
      errors:
      - str
      body: str
      dispatch: str
